/*
 * This file is part of the TSPHP project published under the Apache License 2.0
 * For the full copyright and license information, please have a look at LICENSE in the
 * root folder or visit the project's website http://tsphp.ch/wiki/display/TSPHP/License
 */

package ch.tsphp.parser.test.integration.testutils;

import java.util.Arrays;
import java.util.List;

public class ExpressionHelper
{

    public static List<String[]> getAstExpressions() {
        return Arrays.asList(new String[][]{
                {"$a or $b", "(or $a $b)"},
                {"$a or $b or $c", "(or (or $a $b) $c)"},
                {"$a xor $b", "(xor $a $b)"},
                {"$a xor $b xor $c", "(xor (xor $a $b) $c)"},
                {"$a and $b", "(and $a $b)"},
                {"$a and $b and $c", "(and (and $a $b) $c)"},
                //precedence test
                //($a and $b) or ($c xor $d)
                {"$a and $b or $c xor $d", "(or (and $a $b) (xor $c $d))"},
                //($a or (($b and $c) xor $d)
                {"$a or $b and $c xor $d", "(or $a (xor (and $b $c) $d))"},

                {"$a = $b", "(= $a $b)"},
                {"$a += $b", "(= $a (+ $a $b))"},
                {"$a -= $b", "(= $a (- $a $b))"},
                {"$a *= $b", "(= $a (* $a $b))"},
                {"$a /= $b", "(= $a (/ $a $b))"},
                {"$a &= $b", "(= $a (& $a $b))"},
                {"$a |= $b", "(= $a (| $a $b))"},
                {"$a ^= $b", "(= $a (^ $a $b))"},
                {"$a %= $b", "(= $a (% $a $b))"},
                {"$a .= $b", "(= $a (. $a $b))"},
                {"$a <<= $b", "(= $a (<< $a $b))"},
                {"$a >>= $b", "(= $a (>> $a $b))"},
                {"$a =() $b", "(cAssign $a $b)"},
                //check that all have the same precedence
                {"$a = $b += $c -= $d *= $e", "(= $a (= $b (+ $b (= $c (- $c (= $d (* $d $e)))))))"},
                {"$e /= $f &= $g |= $h ^= $i", "(= $e (/ $e (= $f (& $f (= $g (| $g (= $h (^ $h $i))))))))"},
                {
                        "$i %= $j .= $k <<= $l >>= $m =() $n",
                        "(= $i (% $i (= $j (. $j (= $k (<< $k (= $l (>> $l (cAssign $m $n)))))))))"
                },
                //chaining up simple and compound assignments
                {
                        "$a = $b = $c += $d -= $e = $f *= $g",
                        "(= $a (= $b (= $c (+ $c (= $d (- $d (= $e (= $f (* $f $g)))))))))"
                },
                //precedence test
                //($a = $b) or $c
                {"$a = $b or $c", "(or (= $a $b) $c)"},
                //(($a += $b) and ($c -= $d)) xor $e
                {"$a += $b and $c -= $d xor $e", "(xor (and (= $a (+ $a $b)) (= $c (- $c $d))) $e)"},

                {"true ? $a : $b", "(? true $a $b)"},
                //right associative different than PHP
                {"true ? $a ? $b : $c : $d", "(? true (? $a $b $c) $d)"},
                {"true ? $a : $b ? $c : $d", "(? true $a (? $b $c $d))"},
                //precedence tests
                //($a and ($b = (false ? 1 or 2 : 3)) or 4
                {"$a and $b = false ? 1 or 2 : 3 or 4", "(or (and $a (= $b (? false (or 1 2) 3))) 4)"},
                //$a = (true ? $c += $d : $e) = $f
                {"$a = true ? $c += $d : $e = $f", "(= $a (= (? true (= $c (+ $c $d)) $e) $f))"},
                {
                        //($a *= true ? ($c /= ($d ? $e &= $f : $g) = $h) : $i) or $j
                        "$a *= true ? $c /= $d ? $e &= $f : $g = $h : $i or $j",
                        "(or (= $a (* $a (? true (= $c (/ $c (= (? $d (= $e (& $e $f)) $g) $h))) $i))) $j)",
                },

                {"$a || $b", "(|| $a $b)"},
                {"$a || $b || $c", "(|| (|| $a $b) $c)"},
                {"$a && $b", "(&& $a $b)"},
                {"$a && $b && $c", "(&& (&& $a $b) $c)"},
                {"$a && $b || $c", "(|| (&& $a $b) $c)"},
                {"$a || $b && $c", "(|| $a (&& $b $c))"},
                {"$a || $b && $c ? $d : $e", "(? (|| $a (&& $b $c)) $d $e)"},
                {"$a | $b", "(| $a $b)"},
                {"$a | $b | $c", "(| (| $a $b) $c)"},
                {"$a ^ $b", "(^ $a $b)"},
                {"$a ^ $b ^ $c", "(^ (^ $a $b) $c)"},
                {"$a & $b", "(& $a $b)"},
                {"$a & $b & $c", "(& (& $a $b) $c)"},
                {"$a & $b | $c ^ $d", "(| (& $a $b) (^ $c $d))"},
                {"$a | $b & $c ^ $d", "(| $a (^ (& $b $c) $d))"},
                {"$a == $b", "(== $a $b)"},
                {"$a === $b", "(=== $a $b)"},
                {"$a != $b", "(!= $a $b)"},
                {"$a !== $b", "(!== $a $b)"},

                {"$a < $b", "(< $a $b)"},
                {"$a <= $b", "(<= $a $b)"},
                {"$a > $b", "(> $a $b)"},
                {"$a >= $b", "(>= $a $b)"},
                {
                        "$a == $b | $c < $d & $e ? $f != $g : $h === $i",
                        "(? (| (== $a $b) (& (< $c $d) $e)) (!= $f $g) (=== $h $i))"
                },
                {"1 << 2", "(<< 1 2)"},
                {"1 >> 2", "(>> 1 2)"},
                {"1 >> 2 << 3 >> 5", "(>> (<< (>> 1 2) 3) 5)"},
                {"1 + 2", "(+ 1 2)"},
                {"1 - 2", "(- 1 2)"},
                {"$a . $b", "(. $a $b)"},
                {"$a + $b - $c . $d . $e + $f - $g", "(- (+ (. (. (- (+ $a $b) $c) $d) $e) $f) $g)"},
                {"$a << $b >> $c + $d * $e - $f", "(>> (<< $a $b) (- (+ $c (* $d $e)) $f))"},
                {"!$a", "(! $a)"},
                {"!!$a", "(! (! $a))"},
                {"!!! $a", "(! (! (! $a)))"},
                {"$a instanceof MyClass", "(instanceof $a MyClass)"},
                {"$a instanceof $b", "(instanceof $a $b)"},
                {"(Type) $a", "(casting (type tMod Type) $a)"},
                {"~$a", "(~ $a)"},
                {"@$a", "(@ $a)"},
                {"(Type) (MyClass) $a", "(casting (type tMod Type) (casting (type tMod MyClass) $a))"},
                {"~~$a", "(~ (~ $a))"},
                {"@@$a", "(@ (@ $a))"},
                {"@(Type) ~$a", "(@ (casting (type tMod Type) (~ $a)))"},
                {"+$a", "(uPlus $a)"},
                {"+1", "(uPlus 1)"},
                {"-$a", "(uMinus $a)"},
                {"-2", "(uMinus 2)"},
                {"+$a + $b", "(+ (uPlus $a) $b)"},
                {"-$a - $b", "(- (uMinus $a) $b)"},
                {"clone $a", "(clone $a)"},
                {"clone $a->a", "(clone (memAccess $a a))"},
                {"new Type", "(new Type args)"},
                {"exit", "exit"},
                {"exit(1)", "(exit 1)"},
                {"($a)", "$a"},
                {"$a++", "(postIncr $a)"},
                {"$a--", "(postDecr $a)"},
                {"++$a", "(preIncr $a)"},
                {"--$a", "(preDecr $a)"},
                {"$a", "$a"},
                {"$a->a", "(memAccess $a a)"},
                {"\\foo(1,1+2,3)", "(fCall \\foo() (args 1 (+ 1 2) 3))"},
                {"foo()", "(fCall foo() args)"},
                {"self::foo()", "(mCall self foo() args)"},
                {"parent::foo()", "(mCall parent foo() args)"},
                {"Foo::foo()", "(smCall Foo foo() args)"},
                {"\\a\\foo()", "(fCall \\a\\foo() args)"},
                {"$a->foo()", "(mCall $a foo() args)"},
                {"$a->foo(true || false,123*9)", "(mCall $a foo() (args (|| true false) (* 123 9)))"},
                {"self::$a", "(sMemAccess self $a)"},
                {"parent::$a", "(sMemAccess parent $a)"},
                {"Bar::$a", "(sMemAccess Bar $a)"},
                {"self::a", "(sMemAccess self a#)"},
                {"parent::a", "(sMemAccess parent a#)"},
                {"Foo::a", "(sMemAccess Foo a#)"},
                {"true", "true"},
                {"false", "false"},
                {"null", "null"},
                {"a\\b", "a\\b#"},
                {"1", "1"},
                {"2.123", "2.123"},
                {"'a'", "'a'"},
                {"\"asdf\"", "\"asdf\""},
                {"[1,2,a=>3]", "(array 1 2 (=> a# 3))"},
                {"(int) clone $a + $b", "(+ (casting (type tMod int) (clone $a)) $b)"},
                {"(-$a + $b) * $c", "(* (+ (uMinus $a) $b) $c)"},
                {"!($a instanceof Type) || $a < $b+$c == ~(1 | 3 & 12)", "(|| (! (instanceof $a Type)) (== (< $a (+ " +
                        "$b $c)) (~ (| 1 (& 3 12)))))"}
        });
    }

    public static String[] getParserExpressions() {
        return new String[]{
                "true or false",
                "true xor false",
                "true and false",
                "true or false xor true and false",
                "true ? 1:2",
                "true ? $a<$b ? 1:2:2",
                "true ? $a<$b ? 1:2:2+3-4",
                "true || false",
                "true && false",
                "true || false && true ? true:false",
                "14 | 2",
                "14 ^ 2",
                "14 & 2",
                "9 | 9 ^ 12 & 3",
                "$b = 1",
                "$b += 1",
                "$b -= 1",
                "$b *= 1",
                "$b /= 1",
                "$b %= 1",
                "$b .= 1",
                "$b &= 1",
                "$b |= 1",
                "$b ^= 1",
                "$b <<= 1",
                "$b >>= 1",
                "$b >>= 1",
                "$b==$c",
                "$b!=$c",
                "$b===$c",
                "$b!==$c",
                "$a == $b && $c != $c || $c === $d && $a !== $e",
                "$a < $b",
                "$a <= $b",
                "$a > $b",
                "$a >= $b",
                "$a < 4 && 2 <= 7 || 1 > 10 && 2 >= $d",
                "1 << 4",
                "16 >> 4",
                "$a << 2 >> 5",
                "1+1",
                "2-3",
                "4*5",
                "6/7",
                "6%7",
                "6+7-5*5/(2+1)",
                "6 % 3 + 7-5*5/(2+1)",
                "'hallo'.'welt'",
                "'hallo'.'welt'.\"blabla bla\".$a",
                "!$a",
                "!!$a",
                "$a instanceof Foo",
                "$a instanceof $a",
                "~$a",
                "~~$a",
                "(bool) $a",
                "(int) $a",
                "(float) $a",
                "(string) $a",
                "(array) $a",
                "(Foo) $a",
                "(int) ((bool) $a && $b) + 1",
                "@$a",
                "+1",
                "-1",
                "new a",
                "new a()",
                "clone $a",
                "clone $a->a",
                "clone $a[0]",
                "$a",
                "$a->a",
                "$a[0]",
                "$this",
                "$this->a",
                "$this[0]",
                "foo()->a",
                "$a[0]->a",
                "$a->foo()->a",
                "+foo()",
                "-foo()",
                "+$a->foo()",
                "-$a->foo()",
                "(1+1)",
                "$a++",
                "++$a",
                "--$a",
                "$a--",
                "foo()",
                "a\\foo()",
                "$a->foo()",
                "$a->a->foo()",
                "$a[0]->foo()",
                "$a[0][1]->foo()",
                "self::foo()",
                "self::$a->foo()",
                "parent::foo()",
                "parent::$a->foo()",
                "a",
                "a\\a",
                "A::a"
        };
    }
}
